/**
 * cloud-qmd — make `qmd` use cloud models instead of local GGUF models.
 *
 * How it works
 * ------------
 * pi-memory shells out to `qmd` by name, resolved through PATH. This extension
 * installs a shim (`<agentDir>/bin/qmd`) and prepends that directory to PATH for
 * the pi process, so every `qmd` call from pi-memory lands in the shim:
 *
 *   vsearch / query / embed / update  -> served by cloud models (cloud-qmd engine)
 *   everything else                   -> delegated to the real qmd binary
 *
 * Nothing is monkey-patched, no local model is downloaded, and upgrading qmd
 * cannot break the shim.
 *
 * Commands: /cloud-qmd [status|test|reindex|enable|disable|path|config]
 */

import { spawn } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

// This extension's own directory — known for certain, independent of the env.
const EXT_DIR = path.dirname(fileURLToPath(import.meta.url));

// Where to install the shim / config. An explicit PI_AGENT_DIR wins; otherwise,
// when the extension sits at <agentDir>/extensions/<name>, derive the agent dir
// from this file's location (so a custom install does not fall back to
// ~/.pi/agent); anything else (e.g. `pi -e <clone>`) also uses the default, so a
// checkout is never written to.
const AGENT_DIR = process.env.PI_AGENT_DIR
	? path.resolve(expandHomeEnv(process.env.PI_AGENT_DIR))
	: path.basename(path.dirname(EXT_DIR)) === "extensions"
		? path.dirname(path.dirname(EXT_DIR))
		: path.join(os.homedir(), ".pi", "agent");
const BIN_DIR = path.join(AGENT_DIR, "bin");
const SHIM_PATH = path.join(BIN_DIR, "qmd");
const ENGINE_PATH = path.join(EXT_DIR, "lib", "engine.mjs");
const CONFIG_PATH = process.env.CLOUD_QMD_CONFIG
	? path.resolve(expandHomeEnv(process.env.CLOUD_QMD_CONFIG))
	: path.join(AGENT_DIR, "cloud-qmd.json");

function expandHomeEnv(value: string): string {
	if (value === "~") return os.homedir();
	return value.startsWith("~/") ? path.join(os.homedir(), value.slice(2)) : value;
}

const SHIM_SOURCE = (enginePath: string) => `#!/usr/bin/env node
// cloud-qmd shim — generated by the pi extension extensions/cloud-qmd/index.ts.
// Do not edit by hand: it is rewritten on every pi start.
//
// Semantic commands (vsearch/query/embed/update) are served by cloud models;
// everything else is delegated to the real qmd binary. Delete this file to
// fall back to stock qmd.

const { pathToFileURL } = require("node:url");

const enginePath = ${JSON.stringify(enginePath)};

import(pathToFileURL(enginePath).href)
	.then(async (engine) => {
		const code = await engine.run(process.argv.slice(2));
		process.exit(typeof code === "number" ? code : 0);
	})
	.catch((err) => {
		process.stderr.write(\`cloud-qmd: \${err && err.message ? err.message : String(err)}\\n\`);
		process.exit(1);
	});
`;

const DEFAULT_CONFIG = {
	$comment:
		"cloud-qmd: run `qmd` with cloud models (SiliconFlow by default). Fill in provider.apiKey, then /cloud-qmd test.",
	enabled: true,
	provider: {
		baseUrl: "https://api.siliconflow.cn/v1",
		apiKey: "env:SILICONFLOW_API_KEY",
		embedModel: "BAAI/bge-m3",
		rerankModel: "BAAI/bge-reranker-v2-m3",
		chatModel: "Qwen/Qwen2.5-7B-Instruct",
		timeoutMs: 60000,
	},
	search: {
		chunkTokens: 400,
		chunkOverlapTokens: 80,
		embedBatchSize: 24,
		inlineRefresh: true,
		inlineRefreshDeadlineMs: 10000,
		hybrid: { rrfK: 60, bm25Weight: 1.0, vectorWeight: 1.0 },
		expansion: {
			enabled: true,
			provider: "local",
			variants: 3,
			localModel: "hf:tobil/qmd-query-expansion-0.6B-gguf/qmd-query-expansion-0.6B-q4_k_m.gguf",
			localTimeoutMs: 25000,
			cloudFallback: false,
			hfEndpoint: "https://hf-mirror.com",
		},
		rerank: { enabled: true },
	},
};

interface CloudQmdConfig {
	enabled?: boolean;
	stateDir?: string;
	provider?: { apiKey?: string; baseUrl?: string; embedModel?: string };
	search?: {
		expansion?: {
			enabled?: boolean;
			provider?: "local" | "cloud" | "off";
			localModel?: string | null;
		};
		rerank?: { enabled?: boolean };
	};
}

function readConfig(): CloudQmdConfig {
	try {
		return JSON.parse(fs.readFileSync(CONFIG_PATH, "utf8")) as CloudQmdConfig;
	} catch {
		return {};
	}
}

function writeConfig(mutate: (cfg: Record<string, unknown>) => void): void {
	let raw: Record<string, unknown> = {};
	try {
		raw = JSON.parse(fs.readFileSync(CONFIG_PATH, "utf8")) as Record<string, unknown>;
	} catch {
		raw = structuredClone(DEFAULT_CONFIG) as unknown as Record<string, unknown>;
	}
	mutate(raw);
	fs.mkdirSync(path.dirname(CONFIG_PATH), { recursive: true });
	fs.writeFileSync(CONFIG_PATH, `${JSON.stringify(raw, null, "\t")}\n`);
}

function apiKeyLooksSet(cfg: CloudQmdConfig): boolean {
	const spec = cfg.provider?.apiKey ?? DEFAULT_CONFIG.provider.apiKey;
	if (!spec) return false;
	if (spec.startsWith("env:")) return Boolean(process.env[spec.slice(4)]);
	if (spec.startsWith("file:")) {
		try {
			return fs.readFileSync(expandHomeEnv(spec.slice(5)), "utf8").trim().length > 0;
		} catch {
			return false;
		}
	}
	if (spec.startsWith("$")) return Boolean(process.env[spec.slice(1)]);
	return spec.length > 0;
}

/** Install/refresh the shim and make sure the config template exists. */
function ensureInstalled(): { changed: string[] } {
	const changed: string[] = [];
	if (!fs.existsSync(ENGINE_PATH)) {
		throw new Error(`engine missing at ${ENGINE_PATH} — reinstall the cloud-qmd extension`);
	}
	fs.mkdirSync(BIN_DIR, { recursive: true });

	const desired = SHIM_SOURCE(ENGINE_PATH);
	let current = "";
	try {
		current = fs.readFileSync(SHIM_PATH, "utf8");
	} catch {
		/* missing */
	}
	if (current !== desired) {
		fs.writeFileSync(SHIM_PATH, desired);
		changed.push("shim written");
	}
	fs.chmodSync(SHIM_PATH, 0o755);

	if (!fs.existsSync(CONFIG_PATH)) {
		fs.mkdirSync(path.dirname(CONFIG_PATH), { recursive: true });
		fs.writeFileSync(CONFIG_PATH, `${JSON.stringify(DEFAULT_CONFIG, null, "\t")}\n`);
		try {
			fs.chmodSync(CONFIG_PATH, 0o600); // may hold an API key
		} catch {
			/* best effort */
		}
		changed.push("config created");
	}
	return { changed };
}

/** Put the shim directory first on PATH so pi-memory's `execFile("qmd")` uses it. */
function prependPath(): void {
	const parts = (process.env.PATH ?? "").split(path.delimiter).filter(Boolean);
	if (parts[0] === BIN_DIR) return;
	const rest = parts.filter((p) => p !== BIN_DIR);
	process.env.PATH = [BIN_DIR, ...rest].join(path.delimiter);
}

function runEngine(args: string[], timeoutMs = 180_000): Promise<{ code: number; stdout: string; stderr: string }> {
	return new Promise((resolve) => {
		const child = spawn(process.execPath, [SHIM_PATH, ...args], {
			stdio: ["ignore", "pipe", "pipe"],
			env: process.env,
			timeout: timeoutMs,
		});
		let stdout = "";
		let stderr = "";
		child.stdout.on("data", (d) => {
			stdout += d.toString();
		});
		child.stderr.on("data", (d) => {
			stderr += d.toString();
		});
		child.on("error", (err) => resolve({ code: 1, stdout, stderr: `${stderr}${err.message}\n` }));
		child.on("close", (code) => resolve({ code: code ?? 0, stdout, stderr }));
	});
}

function footerText(): string {
	const cfg = readConfig();
	if (cfg.enabled === false) return "off";
	if (!apiKeyLooksSet(cfg)) return "no key";
	const model = (cfg.provider?.embedModel ?? DEFAULT_CONFIG.provider.embedModel).split("/").pop() ?? "?";
	const expansion = cfg.search?.expansion;
	const expLabel =
		expansion?.enabled === false || expansion?.provider === "off"
			? ""
			: expansion?.provider === "cloud"
				? "cloud-exp"
				: "qmd-exp";
	const extras = [expLabel, cfg.search?.rerank?.enabled === false ? "" : "rank"].filter(Boolean);
	return `${model}${extras.length ? ` +${extras.join("+")}` : ""}`;
}

const HELP = `cloud-qmd — serve qmd's semantic search with cloud models

  /cloud-qmd              show status
  /cloud-qmd test         connectivity + model self-test (needs a valid key)
  /cloud-qmd selftest     offline end-to-end test against a local mock provider
  /cloud-qmd reindex      rebuild the cloud vector index
  /cloud-qmd pull         download the local query-expansion model (one-time, 0.6B ≈ 378 MB)
  /cloud-qmd enable       enable cloud models (stock qmd still handles keyword/FTS)
  /cloud-qmd disable      delegate everything to stock qmd
  /cloud-qmd path         print config/index locations

  CLI equivalent: qmd __cloud status|test|reindex|pull|selftest  •  qmd vsearch|query|embed|update
  Config: ${CONFIG_PATH}`;

export default function (pi: ExtensionAPI) {
	// Install files and route PATH as early as possible: pi-memory resolves `qmd`
	// through PATH on its first search, which can happen during startup.
	let installError: string | undefined;
	try {
		ensureInstalled();
		prependPath();
	} catch (err) {
		installError = err instanceof Error ? err.message : String(err);
	}

	pi.on("session_start", (_event, ctx) => {
		if (installError) {
			ctx.ui.notify(`cloud-qmd: ${installError}`, "error");
			ctx.ui.setStatus("cloud-qmd", "error");
			return;
		}
		prependPath();
		const cfg = readConfig();
		if (cfg.enabled !== false && !apiKeyLooksSet(cfg)) {
			ctx.ui.setStatus("cloud-qmd", "no key");
			ctx.ui.notify(
				`cloud-qmd is installed but has no API key. Add your SiliconFlow key to ${CONFIG_PATH} ` +
					"(provider.apiKey, or export SILICONFLOW_API_KEY), then run /cloud-qmd test.",
				"warning",
			);
			return;
		}
		ctx.ui.setStatus("cloud-qmd", footerText());
	});

	pi.registerCommand("cloud-qmd", {
		description: "Cloud-model qmd: status, test, reindex, enable/disable",
		getArgumentCompletions: (prefix) =>
			["status", "test", "selftest", "reindex", "pull", "enable", "disable", "path", "help"]
				.filter((s) => s.startsWith(prefix))
				.map((s) => ({ value: s, label: s })),
		handler: async (args, ctx) => {
			const sub = (args || "status").trim().split(/\s+/)[0] ?? "status";

			if (sub === "help" || sub === "-h" || sub === "--help") {
				ctx.ui.notify(HELP, "info");
				return;
			}

			if (sub === "enable" || sub === "disable") {
				try {
					writeConfig((cfg) => {
						cfg.enabled = sub === "enable";
					});
				} catch (err) {
					ctx.ui.notify(`cloud-qmd: cannot write ${CONFIG_PATH}: ${(err as Error).message}`, "error");
					return;
				}
				ctx.ui.setStatus("cloud-qmd", footerText());
				ctx.ui.notify(
					sub === "enable"
						? "cloud-qmd enabled: vsearch/query/embed now use cloud models."
						: "cloud-qmd disabled: all qmd commands go to stock qmd.",
					"info",
				);
				return;
			}

			if (sub === "path") {
				ctx.ui.notify(
					`config: ${CONFIG_PATH}\nengine: ${ENGINE_PATH}\nshim:   ${SHIM_PATH}\nindex:  ${readConfig().stateDir ?? path.join(AGENT_DIR, "cloud-qmd")}/index.json`,
					"info",
				);
				return;
			}

			if (sub !== "status" && sub !== "test" && sub !== "reindex" && sub !== "selftest" && sub !== "pull") {
				ctx.ui.notify(`unknown subcommand "${sub}"\n\n${HELP}`, "warning");
				return;
			}

			ctx.ui.setStatus("cloud-qmd", "working…");
			const result = await runEngine(["__cloud", sub]);
			const output = `${result.stdout}${result.stderr}`.trim();
			const failed = result.code !== 0 || /✗|failed|MISSING/.test(output);

			if (sub === "status" || sub === "path") {
				ctx.ui.setStatus("cloud-qmd", footerText());
			} else if (sub === "test") {
				ctx.ui.setStatus("cloud-qmd", failed ? "test failed" : footerText());
			}

			const lines = output.split("\n");
			const shown = lines.length > 24 ? `${lines.slice(0, 24).join("\n")}\n… (${lines.length - 24} more lines)` : output;
			ctx.ui.notify(shown || `cloud-qmd ${sub}: no output`, failed ? "warning" : "info");
		},
	});
}
